#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

GDATA_VER=2.0.17
GDATA_URL=http://gdata-python-client.googlecode.com/files

dl $GDATA_URL/gdata-$GDATA_VER.tar.gz $SRC

WKH_VER=0.12/0.12.2.1
WKH_URL=http://download.gna.org/wkhtmltopdf/$WKH_VER

dl $WKH_URL/wkhtmltox-$(basename $WKH_VER)_linux-jessie-amd64.deb $SRC
