#!/bin/sh -ex

SRC=/usr/local/src

DB_NAME=odoo
DB_USER=odoo
DB_PASS=$(mcookie)

ODOO_USER=odoo
ODOO_PASS=turnkey
ODOO_DIR=/opt/odoo

CONF=/etc/odoo/openerp-server.conf
LOG=/var/log/openerp-server.log

# install wkhtmltox
dpkg -i $SRC/wkhtmltox-*.deb

# install gdata-python-client
cd $SRC
tar -zxvf gdata-*.tar.gz
cd gdata-*
python setup.py install

# start PostgreSQL
/etc/init.d/postgresql start

# create database
#su postgres -c "createuser --no-superuser --createdb --no-createrole $DB_USER"
#su postgres -c "createdb --owner $DB_USER -EUTF8 $DB_NAME"
#su postgres -c "psql postgres" << EOF
#alter user $DB_USER with encrypted password '$DB_PASS';
#EOF
#sed -i "s|.*db_password = .*|db_password = $DB_PASS|" $CONF
su - postgres -c "createuser -s odoo"

# add system user
adduser --system --quiet --shell=/bin/bash --home=$ODOO_DIR --gecos 'ODOO' --group $ODOO_USER
#echo | adduser --disabled-password $ODOO_USER
#usermod -p $(echo $ODOO_PASS | openssl passwd -1 -stdin) $ODOO_USER

update-rc.d openerp-server defaults
ln -s /etc/init.d/openerp-server /etc/init.d/odoo
touch $LOG
chown $ODOO_USER $LOG
chown $ODOO_USER $CONF
chown -R $ODOO_USER:$ODOO_USER $ODOO_DIR

URL=http://127.0.0.1:8069
until $(curl --output /dev/null --silent --head --fail $URL); do
    printf '.'
    service openerp-server start
    sleep 5
done

URL=$URL/web/database/create

DATA='{"jsonrpc":"2.0","method":"call","params":{"fields":[{"name":"super_admin_pwd","value":"admin"},{"name":"db_name","value":"turnkey"},{"name":"db_lang","value":"en_US"},{"name":"create_admin_pwd","value":"turnkey"},{"name":"create_confirm_pwd","value":"turnkey"}]},"id":900757539}'

curl -X POST -H "Content-Type: application/json" -d $DATA $URL

service openerp-server stop

a2enmod proxy_http headers rewrite
a2dissite 000-default
a2ensite odoo

service postgresql stop
